deployment:
  enabled: true
  replicaCount: 1

daemonset:
  enabled: false

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3030

ingressHostName: jena-fuseki

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /
    port: 3030
    scheme: HTTP
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: 3030
    scheme: HTTP
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 10

autoscaling:
  enabled: false

persistence:
  enabled: true
  claimName: "jena-fuseki"
  accessMode: ReadWriteOnce
  size: 3Gi
  annotations:
    "helm.sh/resource-policy": keep

volumes:
  - name: data
    persistentVolumeClaim:
      claimName: "jena-fuseki"

volumeMounts:
  - name: data
    mountPath: "/fuseki"

nodeSelector: {}

tolerations: []

affinity: {}

password: ""
